;[pytest]
;addopts = -vs -m "user_manager"
;testpaths =testcases
;python_files=test_*.py
;python_classes=Test*
;python_functions=test_*
;
;#标记，让测试用例分组执行
;markers=
;    smoke:冒烟用例
;    user_manager:用户管理